name: Build Distribution

on:
  workflow_dispatch:

jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:

    # install dependencies to build the distribution
    - name: install ncc
      run: |
        npm i -g @vercel/ncc

    # checkout the repo
    - name: checkout code
      uses: actions/checkout@v2

    # build the distribution code (dist/index.js)
    - name: build dist
      run: |
        ncc build index.js --license licenses.txt

    # commit the distribution code to a new Branch
    - name: commit dist
      uses: devops-infra/action-commit-push@master
      id: commit
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        add_timestamp: true
        commit_prefix: "[ACTION]"
        commit_message: "Automatic commit"
        force: false
        target_branch: dist/version

    # create a Pull Request from the new Branch
    - name: pull-request-action
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_FROM_BRANCH: ${{ steps.commit.outputs.branch_name }}
        PULL_REQUEST_BRANCH: "main"