name: Test the Action

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
